services:
  postgres:
    container_name: help-desk-nest-clean-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_db: help-desk-nest_clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres 
